package org.example.post


enum class PostVisibility {
    PUBLIC,
    FOLLOWERS,
    PRIVATE
}
enum class MediaType {
    IMAGE, VIDEO
}

enum class ErrorCodes(val code: Long) {

    USERNAME_ALREADY_EXISTS(103),
    USER_NOT_FOUND(104),
    USER_ALREADY_EXISTS(105),
    PASSWORD_IS_INCORRECT(106),
    NOT_LOGGED_IN_EXCEPTION(107),

    FOLLOW_ALREADY_EXISTS(108),
    PHONE_NUMBER_ALREADY_EXISTS(202),

    ORGANIZATION_NOT_FOUND(203),
    ORGANIZATION_NAME_ALREADY_EXISTS(204),

    FOLLOW_NOT_FOUND(204),
    PENDING_ORDER_NOT_FOUND(300),
    FORBIDDEN(301),
    POST_NOT_FOUND(404),

}